### Health
GET http://localhost:8080/healthy

### Criar Cliente
POST http://localhost:8080/clientes
Content-Type: application/json

{
  "nome": "Janduy Monroe",
  "data_nascimento": "1983-06-07T00:00:00Z",
  "telefone": "(98) 996139046",
  "endereco": "Rua Exemplo, 123, Cidade, Estado, 01234-567",
  "email": "janduymonroe@gmail.com"
}

### Buscar todos os clientes
GET http://localhost:8080/clientes

### Buscar cliente por ID
GET http://localhost:8080/clientes/cb86af16-38eb-42fa-95e8-873190026a67