### Health
GET http://localhost:8080/healthy

### Criar Cliente
POST http://localhost:8080/clientes
Content-Type: application/json

{
  "nome": "Janduy Monroe",
  "data_nascimento": "1983-06-07T00:00:00Z",
  "telefone": "(98) 999999946",
  "endereco": "Rua Exemplo, 123, Cidade, Estado, 01234-567",
  "email": "janduymonroe@gmail.com"
}

### Buscar todos os clientes
GET http://localhost:8080/clientes

### Buscar cliente por ID
GET http://localhost:8080/clientes/13bc00bb-5996-43eb-a12b-c6f13addbb35

### Atualizar Cliente
PUT http://localhost:8080/clientes/13bc00bb-5996-43eb-a12b-c6f13addbb35
Content-Type: application/json

{
  "nome": "Pedro F Monroe",
  "data_nascimento": "2013-05-09T00:00:00Z",
  "telefone": "(98) 996139046",
  "endereco": "Rua Exemplo, 123, Cidade, Estado, 01234-567",
  "email": "pedrofmonroe@gmail.com"
}

### Desativar cliente
PATCH http://localhost:8080/clientes/13bc00bb-5996-43eb-a12b-c6f13addbb35

### Remover cliente
DELETE http://localhost:8080/clientes/13bc00bb-5996-43eb-a12b-c6f13addbb35